services:
  - type: web
    name: hackbox-web
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    # Use your custom Docker image
    # Replace "your-username/hackbox-web:latest" with your actual image name
    # image: your-username/hackbox-web:latest
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000