services:
  - type: web
    name: hackbox-web
    env: docker
    # Use the Docker Hub image
    image: primecoder447/hackbox:latest
    # Explicitly tell Render not to use Dockerfile
    dockerfilePath: ""
    dockerContext: ""
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000