services:
  - type: web
    name: hackbox-web
    env: docker
    # Use your local image
    image: dev:latest
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000